#!/usr/bin/env python3
"""Build deterministic ESP32 flash assets and flattened knowledge indexes."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
from typing import Any

if "__file__" in globals():
    PROJECT = Path(__file__).resolve().parents[1]
else:
    Import("env")
    PROJECT = Path(env.subst("$PROJECT_DIR"))
ASSET_ROOT = PROJECT / "assets"
KNOWLEDGE_ROOT = PROJECT / "knowledge"
HEADER = PROJECT / "firmware/include/generated/assets.h"
SOURCE = PROJECT / "firmware/src/generated/assets.cpp"
INDEX = PROJECT / "build/asset_index.json"
AUDIO_EXTENSIONS = {".mp3", ".wav"}
MAX_EMBEDDED_BYTES = 12 * 1024 * 1024
WAV_COMPRESS_THRESHOLD = 2 * 1024 * 1024

SCRIPT_DIR = PROJECT / "scripts"
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))
from prepare_story_audio import prepare_story_audio


def _identifier(path: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9_]", "_", path)
    if value[:1].isdigit():
        value = "asset_" + value
    return "asset_" + value.lower()


def _mime(path: Path) -> str:
    return {
        ".mp3": "audio/mpeg",
        ".wav": "audio/wav",
        ".json": "application/json",
        ".txt": "text/plain",
    }.get(path.suffix.lower(), "application/octet-stream")


def _kind(relative: str) -> str:
    return relative.split("/", 1)[0]


def _compress_wav(path: Path) -> tuple[bytes, str]:
    raw = path.read_bytes()
    if len(raw) <= WAV_COMPRESS_THRESHOLD:
        return raw, path.name
    ffmpeg = shutil.which("ffmpeg")
    if ffmpeg is None:
        raise RuntimeError(
            f"{path} is larger than 2 MiB; install ffmpeg or pre-compress it to MP3"
        )
    with tempfile.TemporaryDirectory() as temporary:
        output = Path(temporary) / (path.stem + ".mp3")
        subprocess.run(
            [ffmpeg, "-v", "error", "-i", str(path), "-ac", "1", "-ar", "22050",
             "-b:a", "64k", "-map_metadata", "-1", str(output)],
            check=True,
        )
        return output.read_bytes(), output.name


def scan_assets() -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for root, prefix in ((ASSET_ROOT, ""), (KNOWLEDGE_ROOT, "knowledge")):
        if not root.exists():
            continue
        for path in sorted(item for item in root.rglob("*") if item.is_file()):
            if path.name.startswith("."):
                continue
            relative = path.relative_to(root).as_posix()
            relative = f"{prefix}/{relative}" if prefix else relative
            data, generated_name = _compress_wav(path) if path.suffix.lower() == ".wav" else (
                path.read_bytes(), path.name)
            if generated_name != path.name:
                relative = str(Path(relative).with_name(generated_name)).replace("\\", "/")
            asset_id = str(Path(relative).with_suffix("")).replace("\\", "/")
            records.append({
                "id": asset_id,
                "path": "/" + relative,
                "kind": _kind(relative),
                "mime": _mime(Path(generated_name)),
                "data": data,
                "sha256": hashlib.sha256(data).hexdigest(),
            })
    return records


def flatten_json(directory: Path) -> list[tuple[str, str, str]]:
    values: list[tuple[str, str, str]] = []
    if not directory.exists():
        return values
    for path in sorted(directory.glob("*.json")):
        document = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(document, dict):
            raise ValueError(f"{path} must contain a JSON object")
        for key, value in sorted(document.items()):
            if not isinstance(value, str):
                raise ValueError(f"{path}: value for {key!r} must be a string")
            values.append((path.stem, str(key), value))
    return values


def _cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def generate() -> None:
    prepare_story_audio(PROJECT)
    records = scan_assets()
    total = sum(len(record["data"]) for record in records)
    if total > MAX_EMBEDDED_BYTES:
        raise RuntimeError(f"embedded assets use {total} bytes; limit is {MAX_EMBEDDED_BYTES}")
    knowledge = flatten_json(KNOWLEDGE_ROOT)
    templates = flatten_json(ASSET_ROOT / "responses")

    HEADER.parent.mkdir(parents=True, exist_ok=True)
    SOURCE.parent.mkdir(parents=True, exist_ok=True)
    INDEX.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(
        "// Generated by scripts/build_assets.py. Do not edit.\n// clang-format off\n#pragma once\n\n"
        "#include <cstddef>\n#include <cstdint>\n\n"
        "namespace teni::generated {\n"
        "struct AssetRecord { const char* id; const char* path; const char* kind; const char* mime; "
        "const std::uint8_t* data; std::size_t size; const char* sha256; };\n"
        "struct KnowledgeRecord { const char* topic; const char* key; const char* value; };\n"
        "struct TemplateRecord { const char* key; const char* value; };\n"
        "extern const AssetRecord kAssets[];\nextern const std::size_t kAssetCount;\n"
        "extern const KnowledgeRecord kKnowledge[];\nextern const std::size_t kKnowledgeCount;\n"
        "extern const TemplateRecord kTemplates[];\nextern const std::size_t kTemplateCount;\n"
        "extern const std::size_t kEmbeddedAssetBytes;\n}  // namespace teni::generated\n// clang-format on\n",
        encoding="utf-8",
    )

    lines = [
        "// Generated by scripts/build_assets.py. Do not edit.",
        "// clang-format off",
        '#include "generated/assets.h"',
        "",
        "namespace teni::generated {",
    ]
    for record in records:
        name = _identifier(record["path"])
        payload = record["data"]
        values = ",".join(f"0x{byte:02x}" for byte in payload) or "0x00"
        lines.append(f"alignas(4) static const std::uint8_t {name}[] = {{{values}}};")
    lines.append("const AssetRecord kAssets[] = {")
    for record in records:
        name = _identifier(record["path"])
        lines.append(
            "  {%s, %s, %s, %s, %s, %d, %s}," % (
                _cpp_string(record["id"]), _cpp_string(record["path"]),
                _cpp_string(record["kind"]), _cpp_string(record["mime"]), name,
                len(record["data"]), _cpp_string(record["sha256"])))
    lines.extend(["};", f"const std::size_t kAssetCount = {len(records)};", ""])
    lines.append("const KnowledgeRecord kKnowledge[] = {")
    lines.extend(f"  {{{_cpp_string(topic)}, {_cpp_string(key)}, {_cpp_string(value)}}},"
                 for topic, key, value in knowledge)
    lines.extend(["};", f"const std::size_t kKnowledgeCount = {len(knowledge)};", ""])
    lines.append("const TemplateRecord kTemplates[] = {")
    lines.extend(f"  {{{_cpp_string(key)}, {_cpp_string(value)}}}," for _, key, value in templates)
    lines.extend([
        "};", f"const std::size_t kTemplateCount = {len(templates)};",
        f"const std::size_t kEmbeddedAssetBytes = {total};",
        "}  // namespace teni::generated", "// clang-format on", "",
    ])
    SOURCE.write_text("\n".join(lines), encoding="utf-8")
    INDEX.write_text(json.dumps({
        "assetCount": len(records), "embeddedBytes": total,
        "limitBytes": MAX_EMBEDDED_BYTES,
        "assets": [{key: value for key, value in record.items() if key != "data"} |
                   {"size": len(record["data"])} for record in records],
        "knowledgeRecords": len(knowledge), "responseTemplates": len(templates),
    }, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"teni assets: {len(records)} files, {total} bytes, {len(knowledge)} knowledge records")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.parse_args()
    generate()


if __name__ == "__main__":
    main()
else:
    # PlatformIO/SCons loads this file as a pre-build script.
    generate()
